<?php

namespace utils\errors;

enum ErrorEnum: int
{
    case SHUTDOWN_EXCEPTION = 0;
    case CONTAINER_MISSING_DEFINITIONS = 1;
    case CONTAINER_CANNOT_RESOLVE_CONSTRUCTOR_PARAMETER_DEPENDENCY = 2;
    case ENVLOADER_FILE_NOT_FOUND = 3;
    case LOGGER_LOG_FILE_NOT_SET = 4;
    case DATABASE_HOST_NOT_SET = 5;
    case DATABASE_USER_NOT_SET = 6;
    case DATABASE_PASS_NOT_SET = 7;
    case DATABASE_NAME_NOT_SET = 8;
    case DATABASE_CONNECTION_ERROR = 9;
    case CACHE_SERVER_NOT_SET = 10;
    case CACHE_VERSION_NOT_SET = 11;
    case CACHE_CONNECTION_ERROR = 12;
    case ROUTE_MISSING_REQUIRED_FIELD = 13;
    case ROUTE_INVALID_FIELD_VALUE = 14;
    case ROUTE_INVALID_JSON_FORMAT = 15;
}
